const API_URL="/api/weather";
const state={rows:[]};
const $=s=>document.querySelector(s);

function icon(t=""){if(t.includes("雷"))return"⛈️";if(t.includes("雨"))return"🌧️";if(t.includes("雪"))return"❄️";if(t.includes("霧"))return"🌫️";if(t.includes("晴時多雲"))return"🌤️";if(t.includes("晴"))return"☀️";if(t.includes("多雲"))return"⛅";if(t.includes("陰"))return"☁️";return"🌈"}
function num(v){if(v==null||v===""||v==="--"||v==="無資料")return null;const n=Number(v);return Number.isFinite(n)?n:null}
function parseRows(data){const locs=data?.records?.Locations?.[0]?.Location||[];return locs.map(l=>{const es=l.WeatherElement||[];const find=n=>es.find(x=>x.ElementName===n);const first=n=>find(n)?.Time?.[0]?.ElementValue?.[0]||{};const p=(l.LocationName||"").split(" ");return{city:p[0]||"未知地區",town:p.slice(1).join(" ")||"代表鄉鎮",temperature:num(first("Temperature").Temperature),humidity:num(first("RelativeHumidity").RelativeHumidity),pop:num(first("ProbabilityOfPrecipitation").ProbabilityOfPrecipitation),windDirection:first("WindDirection").WindDirection??"--",windSpeed:num(first("WindSpeed").WindSpeed),weather:first("Weather").Weather??"資料待更新",start:find("Temperature")?.Time?.[0]?.StartTime||""}})}
function aggregate(rows){const m=new Map();for(const r of rows)if(!m.has(r.city))m.set(r.city,r);return[...m.values()]}
function fmt(v,s=""){return v==null?"--":`${Number.isInteger(v)?v:v.toFixed(1)}${s}`}
function render(){const g=$("#weatherGrid"),q=$("#searchInput").value.trim();g.innerHTML="";const rows=state.rows.filter(r=>`${r.city}${r.town}`.includes(q));if(!rows.length){g.innerHTML='<div class="source-card"><strong>沒有符合的資料</strong><p>請確認搜尋文字或重新取得資料。</p></div>';return}const t=$("#weatherTemplate");for(const r of rows){const n=t.content.cloneNode(true);n.querySelector(".city").textContent=r.city;n.querySelector(".town").textContent=r.town;n.querySelector(".weather-icon").textContent=icon(r.weather);n.querySelector(".temp").textContent=fmt(r.temperature);n.querySelector(".weather-name").textContent=r.weather;n.querySelector(".humidity").textContent=fmt(r.humidity,"%");n.querySelector(".pop").textContent=fmt(r.pop,"%");n.querySelector(".wind-direction").textContent=r.windDirection||"--";n.querySelector(".wind-speed").textContent=fmt(r.windSpeed," m/s");n.querySelector(".forecast-time").textContent=r.start?`預報時間：${new Date(r.start).toLocaleString("zh-TW",{hour12:false})}`:"預報時間：--";g.appendChild(n)}}
function summary(){const ts=state.rows.map(r=>r.temperature).filter(Number.isFinite),hs=state.rows.map(r=>r.humidity).filter(Number.isFinite);$("#cityCount").textContent=new Set(state.rows.map(r=>r.city)).size;$("#recordCount").textContent=state.rows.length;$("#avgTemp").textContent=ts.length?`${(ts.reduce((a,b)=>a+b,0)/ts.length).toFixed(1)} °C`:"--";$("#avgHumidity").textContent=hs.length?`${(hs.reduce((a,b)=>a+b,0)/hs.length).toFixed(1)} %`:"--"}
function status(a,b){$("#statusTitle").textContent=a;$("#statusText").textContent=b}

async function loadWeather(){status("正在取得資料…","正在透過網站後端連線至中央氣象署。");$("#refreshBtn").disabled=true;try{const res=await fetch(API_URL);const data=await res.json().catch(()=>null);if(!res.ok)throw new Error(data?.message||data?.result?.message||`HTTP ${res.status}`);if(data?.success===false)throw new Error(data?.result?.message||data?.message||"CWA API 回傳錯誤");state.rows=aggregate(parseRows(data));if(!state.rows.length)throw new Error("API 有回應，但沒有可顯示的預報資料。");render();summary();$("#updatedAt").textContent=new Date().toLocaleString("zh-TW",{hour12:false});status("資料取得成功",`目前顯示 ${state.rows.length} 個縣市代表資料。`)}catch(e){console.error(e);status("取得資料失敗",e.message)}finally{$("#refreshBtn").disabled=false}}

$("#refreshBtn").addEventListener("click",loadWeather);
$("#searchInput").addEventListener("input",render);
window.addEventListener("load",loadWeather);